name: Foodline
favicon: null
layout_spectrum: 0.8971196543425322
typography_spectrum: 0
title: Foodline - An exploration of cultural influence on food
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#3f3221'
    - '#862900'
    - '#976736'
    - '#dba936'
  brandStrength: 0.905214502941817
  lightness: 0.2541298265568912
  saturation: 0.03035652986727655
  rhythmicContrast: 0.27558269212022424
purpose: []
